import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

import "./globals.css";

import Header from "../components/Header";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TrekMapper",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased background-primary`}
      >
        <Header />
        <main className="flex-1 bg-background-primary">
          <div className="flex flex-col items-center justify-center min-h-[calc(100vh-80px)] h-full min-h-screen">
            <div className="block md:grid grid-cols-12 w-full h-full">
              {/* Left gutter */}
              <div className="col-span-2 hidden md:block bg-gradient-to-r from-black to-background-primary h-full min-h-screen" />
              {/* Main content column */}
              <div className="md:col-span-8 h-full min-h-screen">
                {children}
              </div>
              {/* Right gutter */}
              <div className="col-span-2 hidden md:block bg-gradient-to-l from-black to-background-primary h-full min-h-screen" />
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
